DATA LOADING

In [19]:
import pandas as pd

df = pd.read_csv("C:/Users/shruu/OneDrive/Desktop/Retail_Data_Analysis_and_Data_Warehouse/Retail_Data.csv", encoding='latin1')

In [20]:
print(df.shape)
print(df.columns)
print(df.head())

(9994, 21)
Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')
   Row ID        Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
1       2  CA-2016-152156   11/8/2016  11/11/2016    Second Class    CG-12520
2       3  CA-2016-138688   6/12/2016   6/16/2016    Second Class    DV-13045
3       4  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335
4       5  US-2015-108966  10/11/2015  10/18/2015  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

DATA CLEANING

In [22]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [23]:
df.duplicated().sum()

0

In [24]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [25]:
df['order_date'] = pd.to_datetime(df['order_date'])
df['ship_date'] = pd.to_datetime(df['ship_date'])

In [26]:
df.dtypes

row_id                    int64
order_id                 object
order_date       datetime64[ns]
ship_date        datetime64[ns]
ship_mode                object
customer_id              object
customer_name            object
segment                  object
country                  object
city                     object
state                    object
postal_code               int64
region                   object
product_id               object
category                 object
sub-category             object
product_name             object
sales                   float64
quantity                  int64
discount                float64
profit                  float64
dtype: object

In [27]:
df[['sales', 'profit', 'discount', 'quantity']].describe()

              sales       profit     discount     quantity
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001    28.656896     0.156203     3.789574
std      623.245101   234.260108     0.206452     2.225110
min        0.444000 -6599.978000     0.000000     1.000000
25%       17.280000     1.728750     0.000000     2.000000
50%       54.490000     8.666500     0.200000     3.000000
75%      209.940000    29.364000     0.200000     5.000000
max    22638.480000  8399.976000     0.800000    14.000000

In [28]:
df['profit_margin'] = df['profit'] / df['sales']
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month

EDA

In [29]:
df['sales'].sum()

2297200.8603000003

In [30]:
df.groupby('region')['profit'].sum().sort_values()

region
Central     39706.3625
South       46749.4303
East        91522.7800
West       108418.4489
Name: profit, dtype: float64

In [31]:
df.groupby('region')[['sales','profit']].sum()

               sales       profit
region
Central  501239.8908   39706.3625
East     678781.2400   91522.7800
South    391721.9050   46749.4303
West     725457.8245  108418.4489

In [32]:
df.groupby('region')['discount'].mean()

region
Central    0.240353
East       0.145365
South      0.147253
West       0.109335
Name: discount, dtype: float64

In [33]:
#which category earns more and which loses more money 

df.groupby('category')[['sales','profit']].sum()

                       sales       profit
category
Furniture        741999.7953   18451.2728
Office Supplies  719047.0320  122490.8008
Technology       836154.0330  145454.9481

In [34]:
df.groupby(['region','category'])[['sales','profit']].sum()

                               sales      profit
region  category
Central Furniture        163797.1638  -2871.0494
        Office Supplies  167026.4150   8879.9799
        Technology       170416.3120  33697.4320
East    Furniture        208291.2040   3046.1658
        Office Supplies  205516.0550  41014.5791
        Technology       264973.9810  47462.0351
South   Furniture        117298.6840   6771.2061
        Office Supplies  125651.3130  19986.3928
        Technology       148771.9080  19991.8314
West    Furniture        252612.7435  11504.9503
        Office Supplies  220853.2490  52609.8490
        Technology       251991.8320  44303.6496

In [35]:
# To check why is furniture causing loses 
df[df['category'] == 'Furniture'].groupby('discount')['profit'].mean()

discount
0.00     69.537173
0.10     93.565946
0.15     27.288298
0.20     10.188535
0.30    -48.177103
0.32    -88.560656
0.40   -215.831957
0.45   -226.646464
0.50   -238.355537
0.60    -43.077212
0.70   -259.662627
Name: profit, dtype: float64

AI BASED INSIGHT ENGINE

In [39]:
region_profit = df.groupby('region')['profit'].sum()

avg_profit = region_profit.mean()

for region, profit in region_profit.items():
    if profit < 0:
        print(f"{region} region is incurring losses and needs immediate attention.")
    elif profit < avg_profit:
        print(f"{region} region is underperforming compared to other regions.")
    else:
        print(f"{region} region is performing well with strong profits.")

Central region is underperforming compared to other regions.
East region is performing well with strong profits.
South region is underperforming compared to other regions.
West region is performing well with strong profits.

In [40]:
df.groupby(['region','category'])[['sales','profit']].sum()

                               sales      profit
region  category
Central Furniture        163797.1638  -2871.0494
        Office Supplies  167026.4150   8879.9799
        Technology       170416.3120  33697.4320
East    Furniture        208291.2040   3046.1658
        Office Supplies  205516.0550  41014.5791
        Technology       264973.9810  47462.0351
South   Furniture        117298.6840   6771.2061
        Office Supplies  125651.3130  19986.3928
        Technology       148771.9080  19991.8314
West    Furniture        252612.7435  11504.9503
        Office Supplies  220853.2490  52609.8490
        Technology       251991.8320  44303.6496

In [41]:
category_profit = df.groupby('category')['profit'].sum()

avg_profit = category_profit.mean()

for category, profit in category_profit.items():
    if profit < 0:
        print(f"{category} category is loss-making and needs immediate attention.")
    elif profit < avg_profit:
        print(f"{category} category is underperforming compared to others.")
    else:
        print(f"{category} category is performing well.")

Furniture category is underperforming compared to others.
Office Supplies category is performing well.
Technology category is performing well.

In [46]:
# Dynamic Category Insight
category_profit = df.groupby('category')['profit'].sum()
worst_category = category_profit.idxmin()

print(f"{worst_category} category is the least profitable and needs attention.")

# Dynamic Region Insight
region_profit = df.groupby('region')['profit'].sum()
worst_region = region_profit.idxmin()

print(f"{worst_region} region is underperforming compared to others.")

# Discount Impact
corr = df['discount'].corr(df['profit'])

if corr < -0.5:
    print("There is a strong negative relationship between discount and profit, indicating that higher discounts are significantly reducing profitability.")
elif corr < -0.2:
    print("Discounts have a moderate negative impact on profitability.")
else:
    print("Discounts do not have a significant impact on profitability.")

Furniture category is the least profitable and needs attention.
Central region is underperforming compared to others.
Discounts have a moderate negative impact on profitability.